version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    networks:
      - art-gallery-network
    volumes:
      - ./postgres_db/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: ArtGallery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    networks:
      - art-gallery-network
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG:-0}
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=us-west-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  create-bucket:
    image: amazon/aws-cli
    networks:
      - art-gallery-network
    depends_on:
      - localstack
    environment:
      - AWS_DEFAULT_REGION=us-west-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    entrypoint: >
      sh -c ' aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket art-gallery --create-bucket-configuration LocationConstraint=eu-west-1 '

  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    networks:
      - art-gallery-network
    depends_on:
      - postgres
      - localstack
      - create-bucket
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ArtGallery
      AWS_ACCESS_KEY: test
      AWS_SECRET_ACCESS_KEY: test
      BUCKET_NAME: art-gallery
      S3_LOCAL_URL: http://localstack:4566
      ENV: dev

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    networks:
      - art-gallery-network
    depends_on:
      - backend

networks:
  art-gallery-network:
    driver: bridge
